language: python

python:
  - 3.8

install:
  # pinning coverage package until bugs with coveralls plugin is fixed
  # https://github.com/z4r/python-coveralls/issues/73
  - pip install tox tox-factor wheel python-coveralls "coverage<5.0"

jobs:
  include:
    - stage: test
      script:
        # If we are building from a cron trigger, lets test against live data.
        # This ensures that we run period tests with the latest school website data
        # and can detect and fix any changes to the content as quickly as possible
        - echo Build trigger type is $TRAVIS_EVENT_TYPE
        - '[ "$TRAVIS_EVENT_TYPE" == "cron" ] && export TEST_PARMS="-- --live" || :'
        - export TEST_PARMS="-- --live"
        - tox -f lint
        - tox -f test $TEST_PARMS
        - tox -f docs
        - coveralls

    - stage: deploy-release
      script:
        - pip install twine
        - python setup.py bdist_wheel
        - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS true

    - stage: deploy-snapshot
      script:
        - pip install twine
        - python setup.py bdist_wheel
        - twine upload --repository-url https://test.pypi.org/legacy/
            dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS NOT true